title: Luis Larco
email: luis@luislarco.com
description: >-
  Software Engineer and Musician.
baseurl: ""
url: "https://luislarco.com"
twitter_username: LuisLarco
github_username:  llarco
show_downloads: false
logo: luislarco.jpg

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
